#!/bin/bash
echo -e "\033[1;33m ───────────▄▄▄▄▄▄▄▄▄───────────
────────▄█████████████▄────────
█████──█████████████████──█████
▐████▌─▀███▄───────▄███▀─▐████▌
─█████▄──▀███▄───▄███▀──▄█████─
─▐██▀███▄──▀███▄███▀──▄███▀██▌─
──███▄▀███▄──▀███▀──▄███▀▄███──
──▐█▄▀█▄▀███─▄─▀─▄─███▀▄█▀▄█▌──
───███▄▀█▄██─██▄██─██▄█▀▄███───
────▀███▄▀██─█████─██▀▄███▀────
───█▄─▀█████─█████─█████▀─▄█───
───███────────███────────███───
───███▄────▄█─███─█▄────▄███───
───█████─▄███─███─███▄─█████───
───█████─████─███─████─█████───
───█████─████─███─████─█████───
───█████─████─███─████─█████───
───█████─████▄▄▄▄▄████─█████───
────▀███─█████████████─███▀────
──────▀█─███─▄▄▄▄▄─███─█▀──────
─────────▀█▌▐█████▌▐█▀─────────
────────────███████────────────\e[0m" ;
sleep 3;echo -e "\033[1;33m Para esta instalacion primero debes habilitar el puerto 442 en dropbear!..\e[0m" ;
sleep 2 ; echo -e "\033[1;33m De lo Contrario Sera una instalacion erronea y no funcionara. \e[0m" ;
sleep 2 ;echo -e "\033[1;33m Si no lo habilitaste Presiona CTRL+C para cancelar la instalacion.\e[0m " ;
sleep 2; echo -e "\033[1;33m Tienes 5 segundos \e[0m" ;
sleep 1; echo 1 ;
sleep 1; echo 2 ;
sleep 1 ; echo 3 ;
sleep 1; echo 4 ;
sleep 1; echo 5 ;
echo -e "\033[7;32m INSTALADO SSL + PAY..\e[0m "
apt-get install stunnel4 -y ;
apt-get install stunnel -y ;
cd /etc/stunnel ;
openssl genrsa -out key.pem 2048 ;
sleep 2;echo -e "\033[1;33m Rellenalo a tu gusto.\e[0m";
sleep 2;echo -e "\033[1;33m En Common Name Va tu dominio.\e[0m" ;
openssl req -new -x509 -key key.pem -out cert.pem -days 1095;
cat key.pem cert.pem >stunnel.pem ; wget https://raw.githubusercontent.com/nachorivas581/Nexuser/main/request/stunnel.conf ;
wget https://raw.githubusercontent.com/nachorivas581/Nexuser/main/request/Direct.py ;
sleep 3; echo -e "\033[1;33m INSTALACION COMPLETA.. \e[0m";
sleep 2;echo -e "\033[7;32m Habilitando Servicios\e[0m" ;
sleep 3; service stunnel4 start ; nohup python Direct.py &
sleep 2;echo -e "\033[7;32m Servicios habilitados!\e[0m";
sleep 2;echo -e "\033[7;32m Instalacion Completa!\e[0m";
sleep 2; cd;
sleep 2 ; menu
