#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mNecesitas ejecutar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk='cloudfrontxd.vpsbr.xyz'; _Ink=$(echo '/3Ã—u3#s87r/l32o4Ã—c1aÃ—l1/83Ã—l24Ã—i0bÃ—'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3Ã—u3#sÃ—87r/83Ã—l2Ã—4Ã—i0bÃ—'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mKEY NO VALIDA!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}
echo -e "\033[1;31m-------------------------------------------------------------------\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "Bienvenido al Instalador de [VPS-MOD]" ; tput sgr0
echo -e "\033[1;31m-------------------------------------------------------------------\033[0m"
echo ""
echo -e "             \033[1;31mATENCION! \033[1;33mESTE SCRIPT !\033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mINSTALARA UN CONJUNTO DE HERRAMIENTAS PARA TU VPS\033[0m" 
echo -e "\033[1;33m  PARA QUE  FUNCIONE CORRECTAMENTE\033[0m"
echo ""
echo -e "\033[1;32m \033[1;32m \033[1;33mUTILIZE ESTE SCRIPT BAJO SU PROPIO RIESGO\033[0m"
echo -e "\033[1;33m  DISFRUTA DE LA EXPERIENCIA!\033[0m"
echo ""
echo -e "\033[1;31m--------------------[\033[1;33m \033[1;32mBy Nexuser\033[1;33m [VPS-MOD]\033[1;31m ]------------------------\033[0m"
echo ""
cowsay -f eyes " VPSMOD Nexuser" | lolcat
figlet ..Nexuser.. | lolcat
echo -ne "\033[1;36mKEY DE INSTALACION:\033[1;37m "; read key
_lnk2=$(echo "$key"|awk -F : '{print $2}'); _lnk1=$(echo "$key"|awk -F : '{print $1}')
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $key\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink $_lnk/$_lnk1/$_lnk2/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
sleep 1s
echo ""
cd /root/
apt install speedtest-cli
apt-get install lsof
apt-get install sudo
apt-get install figlet -y
apt-get install cowsay -y
echo -e ""
apt-get install lolcat -y
cd $HOME
apt-get install gawk -y &>/dev/null
apt-get install mlocate -y &>/dev/null
rm $(pwd)/$0 &> /dev/null
 apt-get install nano -y &>/dev/null
 apt-get install bc -y &>/dev/null
 apt-get install screen -y &>/dev/null
 apt-get install python -y &>/dev/null
 apt-get install python3 -y &>/dev/null
 apt-get install curl -y &>/dev/null
 apt-get install ufw -y &>/dev/null
 apt-get install unzip -y &>/dev/null
 apt-get install zip -y &>/dev/null
 apt-get install apache2 -y &>/dev/null
 sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
 service apache2 restart > /dev/null 2>&1 &
sleep 2
  echo Comenzando Instalacion
git clone https://github.com/nachorivas581/INS
chmod +x INS
cd INS
rm /root/Nexuser.sh
sleep 2
cp -r ger-frm /etc
sleep 2
cp -r ger-inst /etc
sleep 2
cp -r newadm /etc
sleep 2
cp -r adm-lite /etc
sleep 2
cd /etc/newadm
sleep 2
touch /etc/newadm/key.txt
sleep 1
echo "$key" > /etc/newadm/key.txt
sleep 1
chmod +x menu
sleep 1
cd
sleep 1
rm -r INS
sleep 1
cd /usr/bin
sleep 1
touch menu
sleep 1
 echo "/etc/newadm/menu" > /usr/bin/menu && chmod +x /usr/bin/menu
sleep 1
chmod -R 777 /etc/ger-frm
sleep 1
chmod -R 777 /etc/ger-inst
sleep 1
chmod -R 777 /etc/newadm
sleep 1 
cd /bin
sleep 1
git clone https://github.com/nachorivas581/BOT.git
sleep 1 
cd bin/BOT/BOT_ADM/request
cp infosys /bin
cp start /bin
cp keygen /bin
cp on-off /bin
cp instal /bin
cp keybot /bin
cp botrun /bin
cp cuentas /bin
cp menu2 /bin
cp crear /bin
sleep 1
cd /bin
chmod +x infosys 
chmod +x start 
chmod +x keygen 
chmod +x on-off 
chmod +x instal
chmod +x keybot
chmod +x botrun
chmod +x menu2
chmod +x cuentas
chmod +x crear
cd /usr/bin
https://raw.githubusercontent.com/nachorivas581/BOT/main/BOT_ADM/request/speedtest.py
chmod +x speedtest.py
cowsay -f eyes " VPSMOD Nexuser" | lolcat
figlet ..Completado.. | lolcat
sleep 2
echo -e "\n\033[1;32mTIPEA menu PARA INICIAR\033[1;32m"




